import { MicrosoftAgentFramework, MicrosoftAgentActivity } from "../lib/microsoft-agent-framework";
import assert from "assert";

export async function runMicrosoftAgentFrameworkTests() {
  const framework = MicrosoftAgentFramework.getInstance();

  // Test 1: Process and Validate Activities
  const activityData: Omit<MicrosoftAgentActivity, "id" | "timestamp"> = {
    type: "message",
    from: { id: "test-user", name: "Test User", role: "user" },
    recipient: { id: "test-agent", name: "Test Agent" },
    text: "Hello from unit test!",
    channelId: "dealflow-a2a",
  };

  const processed = await framework.processActivity(activityData);
  assert.ok(processed.id, "Activity should have an autogenerated UUID id");
  assert.ok(processed.timestamp, "Activity should have an autogenerated ISO timestamp");
  assert.strictEqual(processed.text, "Hello from unit test!");
  assert.strictEqual(processed.from.id, "test-user");

  const activities = framework.getActivities();
  assert.ok(activities.length > 0, "Activities log should contain the processed activity");

  // Test 2: Trigger and Execute GTM Workflows
  const workflow = await framework.startWorkflow(
    "gtm-audit",
    "cust-test-1",
    "Test Client LLC",
    { websiteUrl: "https://testclient.com" }
  );

  assert.strictEqual(workflow.customerId, "cust-test-1");
  assert.strictEqual(workflow.customerName, "Test Client LLC");
  assert.strictEqual(workflow.status, "running");
  assert.strictEqual(workflow.steps.length, 4, "GTM Audit workflow should contain exactly 4 steps");

  // Verify steps structure
  assert.ok(workflow.steps[0].name.includes("Crawl"), "First step should be Crawl");
  assert.ok(workflow.steps[1].name.includes("Analyze"), "Second step should be Analyze");

  // Wait for the background workflow to progress and complete all 4 steps
  await new Promise((resolve) => setTimeout(resolve, 5500));


  const updatedWorkflow = framework.getWorkflow(workflow.id);
  assert.ok(updatedWorkflow, "Should retrieve workflow from cache/store");
  assert.strictEqual(updatedWorkflow.status, "completed", "Workflow should complete successfully after delays");
  assert.strictEqual(updatedWorkflow.currentStepIndex, 3, "Workflow should have executed all steps");

  // Test 3: Performance Telemetry Caching
  const metrics = framework.getPerformanceMetrics();
  assert.ok(metrics.totalRequests > 0, "Metrics should record request counts");
  assert.ok(metrics.cacheHits > 0, "Metrics should record cache hits from getWorkflow calls");
  assert.ok(metrics.hitRate > 0, "Cache hit rate should be greater than zero");
}
